# -*- coding: utf-8 -*-
"""Cópia de Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1U0R0jSNn_h0dWFOXerDfoTJbSVAxy-SE
"""

!pip install transformers

from transformers import BartTokenizer, BartForConditionalGeneration

tokenizer = BartTokenizer.from_pretrained('facebook/bart-large-cnn')
model = BartForConditionalGeneration.from_pretrained('facebook/bart-large-cnn')

text = """
The history of aviation began in the 18th century with the invention of the hot air balloon. Over time, powered flight was developed, leading to the Wright brothers’ success in 1903. Airplanes rapidly evolved, especially during wartime, pushing innovation forward. Today, aviation plays a crucial role in global transportation, commerce, and communication. Modern aircraft are faster, safer, and more efficient than ever before. As technology advances, the future of flight may include electric planes, autonomous systems, and even commercial space travel.
"""

inputs = tokenizer([text], max_length=1024, return_tensors='pt', truncation=True)

summary_ids = model.generate(inputs['input_ids'], max_length=130, min_length=30, length_penalty=2.0, num_beams=4, early_stopping=True)

summary = tokenizer.decode(summary_ids[0], skip_special_tokens=True)
print("Resumo:\n", summary)

